# Site settings
title: The Smiths - We Craft App
email: info@wearesmiths.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wearesmiths.com" # the base hostname & protocol for your site
github_username:  TheSmiths

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
permalink: /:year-:month-:day/:title

# Analytics
analytics :
  provider : google 
    google : 
        tracking_id : 'iUA-11557232-9'
